"""empty message

Revision ID: 6475dd59deb1
Revises: d02bc669dfda
Create Date: 2020-02-16 19:41:37.378973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6475dd59deb1'
down_revision = 'd02bc669dfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genre', new_column_name='genres')
    op.alter_column('Venue', 'genre', new_column_name='genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres', new_column_name='genre')
    op.alter_column('Venue', 'genres', new_column_name='genre')
    # ### end Alembic commands ###
